// TODO: Include packages needed for this application
const inquirer = require('inquirer');
const fs = require('fs');
const generateMarkdown = require('./utils/generateMarkdown');

// TODO: Create an array of questions for user input
const questions = () => {
    return inquirer.prompt([
        {
            type: 'input',
            name: 'name',
            message: 'What is this project called?'
        },
        {
            type: 'input',
            name: 'description',
            message: 'Describe this application'
        },
        {
            type: 'input',
            name: 'installation',
            message: 'Enter the installation instructions'
        },
        {
            type: 'input',
            name: 'usage',
            message: 'Enter the usage information for the project.'
        },
        {
            type: 'input',
            name: 'contributing',
            message: 'Enter the contribution guidelines.'
        },
        {
            type: 'input',
            name: 'tests',
            message: 'Enter the testing instructions.'
        },
        {
            type: 'list',
            name: 'license',
            message: 'Choose from the following licenses: ',
            choices: ['MIT', 'Amazon', 'Apache', 'GLI', 'None']
        },
        {
            type: 'input',
            name: 'email',
            message: 'Enter your email address.'
        },
        {
            type: 'input',
            name: 'github',
            message: 'Enter your GitHub username.'
        },

    ]);
};

const generateFile = ({name, description, installation, usage, contributing, tests, license, email, github}) =>
` 
# ${name}

Table of Contents:
* [Description](#Description)
* [Installation](#Installation)
* [Usage](#Usage)
* [Contributing](#Contributing)
* [Tests](#Tests)
* [License](#License)
* [Questions](#Questions)

## Description

${description}

## Installation

${installation}

## Usage

${usage}

## Contributing

${contributing}

## Tests

${tests}

## License 

This project is under the ${license} license.

## Questions

Have any questions? Please send them to ${email}.
This project's code can be viewed at https://github.com/${github}.
`;

const init = () => {
    questions()
    .then((answers) => fs.writeFileSync('AutoGeneratedReadMe.md', generateMarkdown(answers)))
    .then(() => console.log('Your ReadMe file has been generated!'))
    .catch((err) => console.error(err));
}

init();






















